# Generated by Django 5.0.3 on 2025-06-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('company_name', models.CharField()),
                ('licence_no', models.CharField()),
                ('address', models.CharField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
