# Generated by Django 5.0.3 on 2025-06-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_safaripackage_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaripackage',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='safari_packages/'),
        ),
    ]
