# Generated by Django 5.0.3 on 2025-06-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_safaripackage_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safaripackage',
            name='picture',
            field=models.ImageField(upload_to='safari_packages/'),
        ),
    ]
