# Generated by Django 5.0.3 on 2025-06-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('tour_package_id', models.IntegerField()),
                ('num_people', models.IntegerField()),
                ('start_date', models.DateField()),
                ('status', models.TextField(max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
